# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
 # - oraclejdk8
  - openjdk8

# используем режим обычного пользователя для сборки проекта.
sudo: false

#script: mvn clean verify

env:
  global:
    - CODECOV_TOKEN="1d3c3061-e15d-4bb7-a14f-54d633c24484"

services:
  - postgresql

before_install:
  - psql -c 'create database requests;' -U postgres

#before_script:
#  - psql -c 'create database requests;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту mailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mailto:gvg_java@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always